server:
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 200
      min-spare: 30
    connection-timeout: 5000ms
  port: 8080
  servlet:
    context-path: /emos

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://47.96.7.148:8066/MEET?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: mycat
      password: mycat!BrWCrxPh0Vq
      initial-size: 8
      max-active: 16
      min-idle: 8
      max-wait: 60000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false

  redis:
    database: 0
    host: 148.70.115.4
    port: 6379
    password: MX5rlP9I62
    jedis:
      pool:
        max-active: 1000
        max-wait: -1ms
        max-idle: 16
        min-idle: 8

  data:
    mongodb:
      host: 47.96.7.148
      port: 27017
      database: meeting
      authentication-database: admin
      username: meeting
      password: 123456
  mail:
    default-encoding: UTF-8
    host: smtp.aliyun.com
    username: cqlwm_dev@aliyun.com
    password: 147258az
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: org.lpro.emos.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

logging:
  level:
    root: info
    com.example.emos.wx.db.dao : warn
  pattern:
    console: "%d{HH:mm:ss}  %-5level  %msg%n"

emos:
  jwt:
    secret: abc123456
    expire: 5
    cache-expire: 10
  face:
    createFaceModelUrl: http://192.168.99.101:3000/create_face_model
    checkinUrl: http://192.168.99.101:3000/checkin
  email:
    system: ABC@aliyun.com
    hr: ABC@qq.com
  image-folder: D:/emos/image
  code: xxxxx

wx:
  app-id: xxxxx
  app-secret: xxxxx